### ISSUE TITLE
Typo In the Documentation

### ISSUE THREAD

**Issue by sparrow007** [skydoves/compose-performance#2]
We have a typo in the documentation "Understandinf" that should be "Understanding" .
<img width="1005" alt="Screenshot 2024-07-31 at 1 17 29 AM" src="https://github.com/user-attachments/assets/e4bec747-1581-43ac-9ef4-25f18fe18d29">

Please check this thanks

**Comment by skydoves** [comment]
Hey @sparrow007, it has been fixed. Thank you for raising this issue!
